# Generated by Django 3.2.5 on 2021-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, default='', max_length=100)),
                ('item', models.CharField(blank=True, default='', max_length=100)),
                ('total', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
    ]
