# Generated by Django 3.2.5 on 2021-07-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_file', '0002_alter_csvmodel_csv_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='csv_fields',
            field=models.FileField(upload_to=''),
        ),
    ]
